modLoader="javafml"
loaderVersion="[40,)"
license="MIT License"

[[mods]]
modId="piseks_shulkerbacks"
version="1.0.1"
displayName="Pisek's ShulkerBacks"
credits="Source code: https://github.com/Piseks-Mods/ShulkerBacks/"
displayURL="https://www.curseforge.com/minecraft/mc-mods/piseks-shulkerbacks"
logoFile="logo.png"
authors="Písek Pískovec"
description='''
Put your special Shulker Box on your back.
'''

[[dependencies.piseks_shulkerbacks]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




